version: '3.8'

services:
  exam-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # 如果需要PostgreSQL，可以取消注释下面的配置
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: exam_backend
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: 